apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-v2
  labels:
    app: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
      version: "2.0.0"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-app
        version: "2.0.0"
    spec:
      containers:
      - name:  go-app-ctr
        image: sergividal/go-app
        resources:
          limits:
            cpu: 100m
            memory: "256Mi"
          requests:
            cpu: 100m
            memory: "256Mi"
