apiVersion: v1
kind: Service
metadata:
  name: go-app
spec:
  selector:
    app: go-app
    version: "1.0.0"
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000